### ISSUE TITLE
计算 GSOP

### ISSUE THREAD

**Issue by Jee-King** [fangwei123456/Spike-Element-Wise-ResNet#17]
hi，我在openreview上的rebuttal中看到你们提供了关于耗能的计算。所以我想咨询一下snn的GSOP是怎么计算的，他和相同结构的ann网络FLOPS有关系吗?  谢谢！

**Comment by fangwei123456** [comment]
https://github.com/fangwei123456/spikingjelly/discussions/211

SOP=发放率*FLOP
功耗=一个SOP的功耗 \* 发放率 \* 发放次数

**Comment by Jee-King** [comment]
谢谢，我去了解一下！

**Comment by fangwei123456** [comment]
也可以参考一下这个

https://github.com/fangwei123456/spikingjelly/issues/348
