### ISSUE TITLE
dvsgesture 数据集加载时 gesture_mapping.csv 文件md5错误

### ISSUE THREAD

**Issue by dfxue** [fangwei123456/Spike-Element-Wise-ResNet#20]
我已经把 DvsGesture.tar.gz 下载到服务器了，并且进行了解压，但是在代码里加载数据时发现 gesture_mapping.csv 文件的 md5 错误， DvsGesture.tar.gz 的 md5 是通过的，解压出来的 csv 文件也没改，想请教下大佬们遇到过这个问题吗？改如何解决？谢谢
![image](https://user-images.githubusercontent.com/17716458/232854920-9f1ad303-d18f-402a-bd28-591f739a1902.png)

**Comment by fangwei123456** [comment]
![image](https://user-images.githubusercontent.com/38352109/233012472-fff31ef9-57b2-4ebe-94d8-ea162cfac23a.png)

**Comment by dfxue** [comment]
您好：    您发送的邮件已经收到。
