### ISSUE TITLE
spikingjelly（安装问题）

### ISSUE THREAD

**Issue by Katherine-Cao** [fangwei123456/Spike-Element-Wise-ResNet#4]
hello ，where should i download the package spikingjelly？whether I need to download  spikingjelly in the environment of Anaconda configuration or any folder?（请问spikingjelly 是在下载anaconda配置的环境中还是任意一个文件夹即可？）

**Comment by fangwei123456** [comment]
任意一个文件夹即可，执行安装命令后，包会被复制到conda的env路径下。
