### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by ZAcerOne** [fangwei123456/Spike-Element-Wise-ResNet#5]
![image](https://user-images.githubusercontent.com/67686297/149608815-99c853aa-5914-4b6e-a9ba-50a0207ec980.png)
你好，请问这个图片上的问题要如何解决？
Cuda=10.1 torch=1.7.1

**Comment by fangwei123456** [comment]
conv2d报错，尝试减少batch size和T试试看能否正常运行

**Comment by ZAcerOne** [comment]
![image](https://user-images.githubusercontent.com/67686297/149609207-2ce4eefd-879f-4fd0-80b3-7390fe06f7b5.png)
然后就出现了这个错误  把replace=False 改成了True之后又报了RuntimeError: CUDA error: invalid device function这个错误

**Comment by fangwei123456** [comment]
T_train设置为None试一下

**Comment by ZAcerOne** [comment]
T_train需要int类型的参数  设置为0的话就会出现RuntimeError: CUDA error: invalid device function
![image](https://user-images.githubusercontent.com/67686297/149609411-6a8aabec-6ceb-4052-9a79-eff025c98927.png)

**Comment by fangwei123456** [comment]
T_train=None的时候是不会执行这一句的
https://github.com/fangwei123456/Spike-Element-Wise-ResNet/blob/4ffb89945802cb9509a118393647347337663422/dvsgesture/train.py#L39

**Comment by ZAcerOne** [comment]
![image](https://user-images.githubusercontent.com/67686297/149610081-10416bfd-86f3-4823-ad0c-3b5f6c53684f.png)
![image](https://user-images.githubusercontent.com/67686297/149610106-2457f204-3133-4536-b4a5-3f805dd0f218.png)
当T_Train= None 的时候就会出现 RuntimeError: CUDA error: invalid device function

**Comment by fangwei123456** [comment]
T和batch size分别是多少？

**Comment by ZAcerOne** [comment]
![image](https://user-images.githubusercontent.com/67686297/149611705-5e2b902f-2fc4-41e4-902b-ccf1589bbfe8.png)
全部都调整为1也还是不行...还是一样的报错

**Comment by fangwei123456** [comment]
普通的卷积都报错，不应该的。。可以装CUDA10.2吗，004版本的SJ框架应该是按CUDA11设计的，但CUDA10.2应该也能跑

**Comment by ZAcerOne** [comment]
调整到CUDA10.2，可以运行了，谢谢。
